version: "3.9"
services:
  vulnerable-site:
    build: ./vulnerable-site
    ports:
      - "5000:5000"
    restart: unless-stopped

  attacker-site:
    build: ./attacker-site
    ports:
      - "4000:4000"
    restart: unless-stopped
